#!/usr/bin/env bash

source "$(dirname "$0")/../lib/platform.sh"

case "$OS" in
    ubuntu)
        # Docker apt repository
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl

        sudo install -m 0755 -d /etc/apt/keyrings

        sudo curl -fsSL \
            https://download.docker.com/linux/ubuntu/gpg \
            -o /etc/apt/keyrings/docker.asc

        sudo chmod a+r /etc/apt/keyrings/docker.asc

        echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            ${VERSION_CODENAME} stable" |
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

        install_packages \
            docker-ce \
            docker-ce-cli \
            containerd.io \
            docker-buildx-plugin \
            docker-compose-plugin
        ;;

    fedora)
        # Docker dnf repository
        sudo dnf -y install dnf-plugins-core

        sudo dnf config-manager addrepo --from-repofile=https://download.docker.com/linux/fedora/docker-ce.repo

        install_packages \
            docker-ce \
            docker-ce-cli \
            containerd.io \
            docker-buildx-plugin \
            docker-compose-plugin
        ;;
esac
