set -g default-terminal "tmux-256color"
set -s escape-time 0

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g status-style 'bg=#333333 fg=#5eacd3'
set -g base-index 1

bind e copy-mode

set -g set-clipboard off
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'wl-copy'

bind r source-file ~/.config/tmux/tmux.conf \; run-shell "notify-send 'Tmux' 'Config reloaded!'"
bind -r o new-window -c '#{pane_current_path}'

bind f new-window "$HOME/.local/bin/tmux-sessionizer"
bind i popup -E "$HOME/.local/scripts/misc/cheat"
